### ISSUE TITLE
[Feat] 토글 컴포넌트 추가

### ISSUE THREAD

**Issue by task-er** [ecolink-JOIN/JOIN-FE#15]
## 목적

> 공통 컴포넌트 개발

## 작업 상세 내용
- 여기 있는 토글들 추가
![image](https://github.com/user-attachments/assets/0c974f11-e3c2-453c-8575-94ef10c2f4d8)

## 참고 사항
https://www.figma.com/design/zJQOoIOUmPPNa5aximiuAZ/%EC%8A%A4%ED%84%B0%EB%94%94-%ED%94%8C%EB%9E%AB%ED%8F%BC-_JOIN?node-id=614-3097&t=lSytJvz65AKcCHf2-0

**Comment by PROMLEE** [comment]
- [ ]
